export enum QueryKeys {
  ME = "me",
  USERS = "users",
  WELLS = "wells",
  PERIODS = "periods",
  EFFICIENCY = "efficiency",
  EFFICIENCIES = "efficiencies",
  BILLING = "billing",
  BILLINGS = "billings",
  CONTRACT_RIGS = "contract-rigs",
  CONFIG_BILLINGS = "config-billings",
  SYSTEM_VERSION = "system-version",
  UNBILLED_PERIODS = "unbilled-periods",
  DELETION_REQUESTS = "deletion-requests",
  TEMPORARY_EFFICIENCY = "temporary-efficiency",
  TEMPORARY_EFFICIENCIES = "temporary-efficiencies",
}
